


//SOMETIMES (NOT OFTEN) WIFICLIENT NEEDS LND SSL, IT MUST BE IN THIS FORMAT


const char* tlscert =   
"-----BEGIN CERTIFICATE-----\n" \
"MIICGTCCAcCgAwIBAgIQRz1oxLcP6vTVYgj/Cz4mYjAKBggqhkjOPQQDAjA3MR8w\n" \
"HQYDVQQKExZsbmQgYXV0b2dlbmVyYXRlZCBjZXJ0MRQwEgYDVQQDEwtyYXNwYmVy\n" \
"cnlwaTAeFw0yMDA2MjgyMzM4MjFaFw0yMTA4MjMyMzM4MjFaMDcxHzAdBgNVBAoT\n" \
"FmxuZCBhdXRvZ2VuZXJhdGVkIGNlcnQxFDASBgNVBAMTC3Jhc3BiZXJyeXBpMFkw\n" \
"EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyR0Dv9DRwImk1UPZoRNegOq+qkMJEhnp\n" \
"nofn3ojQHkQPF4HVgG0DjGogemas9CeZA2gfApK6FT9MhPRhpZnad6OBrTCBqjAO\n" \
"BgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUw\n" \
"AwEB/zByBgNVHREEazBpggtyYXNwYmVycnlwaYIJbG9jYWxob3N0ggR1bml4ggp1\n" \
"bml4cGFja2V0ggdidWZjb25uhwR/AAABhxAAAAAAAAAAAAAAAAAAAAABhwTAqLJf\n" \
"hxD+gAAAAAAAAJCDb2vQjLxphwQDf7wyMAoGCCqGSM49BAMCA0cAMEQCIDTRZGjm\n" \
"oI6QCkod2lKw6FNz2jvFqsOwI8X7Xzt1xTh2AiBI/rhrmXp++3G4+LvgrfAgDFRI\n" \
"niAOZRBdbPTEZIBvNw==\n" \
"-----END CERTIFICATE-----\n";
